export const FLUX_WEBHOOK_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApItGFqrPP65bhoIXh5Aj
ruqLxUljdcwESTSJJllDtwXeHJcxf6qBXWmK3mPMsXuCsCRY8cOKAbqzrylWohoG
wC+de3w7FMUVH+UH8B+s6OZVzGXKhYnhlq6IVJaw7ZHTZDQUBOtQIYA6pd5YYIXv
rP2rtvxrlQ/TtUor3InwuZvnZGPdRGkcnl8G+QIbMzxrq4sMeJlL64Mx5cqg8VrR
MGCD4eWD5dtOn3ys9uc7SxMoNl4UmZfprS3C2wsD3RpSRSn/ZCr9SOr4dZVj0GhW
d1z3D7Yvfn5oqe7Uy9Lw2Jfu2YFhiYOex1lhKa2uVAd4yEUguyCRL3AlXw4rex2/
wQIDAQAB
-----END PUBLIC KEY-----
`;

export const FLUX_TIER_SILVER_PRODUCT_ID = "prod_OaI1b3B0z0Y3yY";
export const FLUX_TIER_GOLD_PRODUCT_ID = "prod_OaI1b3B0z0Y3yY";
